In [ ]:
import tensorflow as tf
sample=tf.constant("hello world")
print("Tensor:",sample)
print("value:",sample.numpy())

Tensor: tf.Tensor(b'hello world', shape=(), dtype=string)
value: b'hello world'


In [ ]:
a=tf.ones([2,3])
print(a)
a=tf.Variable(a)
#print(a)
a[0,0].assign(10.45)
b=a.read_value()
print(b)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[10.45  1.    1.  ]
 [ 1.    1.    1.  ]], shape=(2, 3), dtype=float32)


\#### =========== add , multi , div , etc ..... =========== #### 

In [ ]:
a=tf.constant(2)
b=tf.constant(3)

In [ ]:
print("a+b:",a.numpy()+b.numpy())
print("addition with constants:",a+b)
print("a*b:",a.numpy()*b.numpy())
print("multiplication with constants:",a*b)
print("multiplication with constants:",tf.multiply(a,b))

a+b: 5
addition with constants: tf.Tensor(5, shape=(), dtype=int32)
a*b: 6
multiplication with constants: tf.Tensor(6, shape=(), dtype=int32)
multiplication with constants: tf.Tensor(6, shape=(), dtype=int32)


In [41]:
matrix1=tf.constant([[3,3]])
matrix2=tf.constant([[2],[2]])
product=tf.matmul(matrix1,matrix2)
print("brodcast matrix in multiplication:",matrix1,matrix2)
print("multiplication of matrix:",product)

brodcast matrix in multiplication: tf.Tensor([[3 3]], shape=(1, 2), dtype=int32) tf.Tensor(
[[2]
 [2]], shape=(2, 1), dtype=int32)
multiplication of matrix: tf.Tensor([[12]], shape=(1, 1), dtype=int32)


#### ================cast operations================ ####

In [45]:
a=tf.convert_to_tensor(2)
b=tf.cast(a,tf.int32)
print(a,b)

tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(2, shape=(), dtype=int32)


#### =============shape operations============= ####

In [51]:
a=tf.ones([2,3])
print(a.shape[0],a.shape[1])
shape=tf.shape(a)
print(shape)

2 3
tf.Tensor([2 3], shape=(2,), dtype=int32)
